Code,Description
"9E","Endeavor Air Inc."
"AA","American Airlines Inc."
"AS","Alaska Airlines Inc."
"B6","JetBlue Airways"
"DL","Delta Air Lines Inc."
"EV","ExpressJet Airlines Inc."
"F9","Frontier Airlines Inc."
"FL","AirTran Airways Corporation"
"MQ","Envoy Air"
"NK","Spirit Air Lines"
"OO","SkyWest Airlines Inc."
"UA","United Air Lines Inc."
"US","US Airways Inc."
"VX","Virgin America"
"WN","Southwest Airlines Co."
"YV","Mesa Airlines Inc."
